### ISSUE TITLE
Getter with lean({virtuals: true}) is missing in the result

### ISSUE THREAD

**Issue by aviadhadidainx** [vkarpov15/mongoose-lean-virtuals#25]
When i use lean with virtuals: true i would expect the getter will be also reflected in the result.

I couldn't find anything in the documentation so i am not sure how i can tackle this issue.
I am using Decimal128 type and i need to get it as real double to avoid conversions across the code.

Any help will be appreciated.
Thanks

**Comment by aviadhadidainx** [comment]
I can see that this logic is missing.
I just added this piece of code the `attachVirtualsToDoc`

`  // Apply getters of the result
  const schemObject = schema.obj
  const schemObjectKeys = Object.keys(schemObject);
  for (const key of schemObjectKeys) {
    if (schemObject[key].get) {
      doc[key] = schemObject[key].get.call(doc, doc[key])
    }
  }`

I am far from being aware to the logic here so i cannot create pull request with high cofidence that i a not messing up other things.

Can you consider add this feature? Or there is something i am missing here?
Maybe there is a workaround?

**Comment by vkarpov15** [comment]
I'd consider that a separate use case, this plugin is specifically for virtuals. We might need a separate plugin for getters...

**Comment by aviadhadidainx** [comment]
Thanks!

**Comment by makinde** [comment]
This commit (https://github.com/vkarpov15/mongoose-lean-virtuals/commit/d240f3c1ce404ce7bf87a0c886a47fa38cb50b7b) actually attempts to address this issue. After @vkarpov15 and I discussed, getter functionality on virtual should be fully encapsulated in `mongoose-lean-virtuals` and not `mongoose-lean-getters`. I’m including my full description of the issue and test case that currently breaks.

~~~

When you run the following code, you’ll get the following result.

```js

'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const childSchema = Schema({ name: String, parentId: 'ObjectId' });
  const Child = mongoose.model('Child', childSchema);

  const parentSchema = Schema({ name: String });
  parentSchema.virtual('children', {
    ref: 'Child',
    localField: '_id',
    foreignField: 'parentId'
  });
  parentSchema.virtual('children').getters.unshift(function(v) {
    console.log('Children virtual getter called!');
    return v;
  });
  parentSchema.plugin(require('mongoose-lean-virtuals'));
  const Parent = mongoose.model('Parent', parentSchema);

  const p = await Parent.create({ name: 'Darth Vader' });
  const c = await Child.create({ name: 'Luke Skywalker', parentId: p });

  const doc = await Parent.findOne().populate('children').lean({ virtuals: true });
  console.log(doc);
}
```

```
Children virtual getter called!
{
  _id: 5e926d7771dee07298052b37,
  name: 'Darth Vader',
  __v: 0,
  children: undefined,
  id: '5e926d7771dee07298052b37'
}
```

Not that `children` is `undefined`. That's because the default getter on a virtual expects to get the existing value passed in as the first parameter when there is a lean query. This is was `mongoose-lean-getters` does. But here (line 116), `void 0` is passed as the first param to `applyGetters`. That needs to be the current value of the field from the object. For normal queries, that value will be undefined (I think), but for lean queries, it should be the actual field.
